
export interface Book {
  id: string;
  userId?: string; 
  title: string;
  author: string;
  coverUrl: string;
  progress: number;
  totalPages?: number;
  totalTime?: string;
  content?: string; 
  isAnalyzed?: boolean; 
  isPremium?: boolean; 
  price?: number; 
  // New: For practice drills
  category?: 'practice' | 'user';
  difficulty?: 'Fácil' | 'Medio' | 'Difícil';
  questions?: QuizQuestion[];
}

export interface UserPreferences {
  dailyGoalMinutes: number;
  targetWPM: number;
  difficultyLevel: 'Básico' | 'Intermedio' | 'Avanzado';
  notificationsEnabled: boolean;
  soundEnabled: boolean;
  themeColor?: string;
  unlockedRewards?: string[];
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: string;
  unlockedAt?: number;
}

export interface Reward {
  id: string;
  type: 'avatar' | 'theme' | 'book';
  title: string;
  description: string;
  cost: number;
  value: string;
  icon: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  avatarUrl: string;
  stats: UserStats;
  joinedDate: number;
  baselineWPM: number;
  level: string; 
  preferences: UserPreferences;
  achievements: Achievement[];
}

export interface UserStats {
  streak: number;
  tel: number; // Tasa de Eficiencia Lectora (KPI Principal)
  lastActiveDate: number; 
  xp: number; 
  maxSchulteLevel?: number; 
  maxWordSpan?: number; 
}

export interface Notification {
  id: string;
  title: string;
  message: string;
  type: 'info' | 'success' | 'warning' | 'error';
  timestamp: number;
  isRead: boolean;
}

// Phase 3: Expanded Metrics
export interface ReadingLog {
  id: string;
  userId: string;
  exerciseType: 'schulte' | 'reading_session' | 'rsvp' | 'word_span' | 'loci';
  levelOrSpeed: number; 
  durationSeconds: number;
  wpmCalculated?: number;
  comprehensionRate?: number; 
  telCalculated?: number; // WPM * Comprehension
  
  // New Adaptive Metrics
  fixationTimeAvg?: number; // ms average per click/word
  errors?: number; // wrong clicks or false recalls
  contentCategory?: 'fiction' | 'non_fiction' | 'technical';
  
  timestamp: number;
}

export interface RetentionLog {
  id: string;
  userId: string;
  flashcardId: string;
  rating: number; 
  intervalDays: number;
  timestamp: number;
}

// Phase 3: Memory Architecture (RAG-lite)
export interface MemoryConcept {
  id: string;
  bookId: string;
  originalTextChunk: string;
  extractedFact: string; // The "truth" extracted by LLM
  question: string;
  answer: string;
  difficulty: number; // 1-10
}

export interface Flashcard {
  id: string;
  userId?: string; 
  bookId?: string;
  front: string; 
  back: string;  
  interval: number; 
  repetition: number; 
  efactor: number; 
  dueDate: number; 
  // Link to concept if generated by AI
  conceptId?: string;
}

export interface QuizOption {
  id: string;
  text: string;
  isCorrect: boolean;
  explanation?: string;
}

export interface QuizQuestion {
  id: number;
  question: string;
  imageUrl?: string;
  options: QuizOption[];
}

// --- New Training Structure ---
export interface TrainingModule {
    id: string;
    title: string;
    description: string;
    icon: string;
    route: AppRoute;
    colorClass: string; // e.g., 'text-blue-500 bg-blue-500/10'
    metrics: {
        label: string;
        key: 'maxLevel' | 'avgTime' | 'totalSessions' | 'bestScore';
        unit?: string;
    }[];
}

export enum AppRoute {
  WELCOME = 'welcome',
  LOGIN = 'login',
  REGISTER = 'register',
  ASSESSMENT_INTRO = 'assessment_intro',
  ASSESSMENT_READING = 'assessment_reading',
  ASSESSMENT_QUIZ = 'assessment_quiz',
  ASSESSMENT_RESULTS = 'assessment_results',
  DASHBOARD = 'dashboard',
  LIBRARY = 'library',
  READING = 'reading',
  SCHULTE = 'schulte',
  WORD_SPAN = 'word_span',
  MEMORY_TRAINING = 'memory_training',
  LOCI_TRAINING = 'loci_training',
  SETTINGS = 'settings',
  EDIT_PROFILE = 'edit_profile',
  REWARDS = 'rewards',
  TRAININGS = 'trainings', // New Route
}
